class ContentList {
  List<String> movies = [
    "တရုတ်နိုင်ငံရဲ့ အချက်ပေါင်း 101 ချက် - တရုတ်ပြည်အကြောင်းအလုံးစုံ (China)",
    "C001 Battle.Creek.Brawl.1980.REMASTERED (China)",
    "C002 Crime.Story-1993 (China)",
    "C003 Dragon.Lord.1982BluRay (China)",
    "C004 Hidden Strike. 2023 (China)",
    "C005 TAN Chi Master (China)",
    "C006 The Forbidden Kingdom (China)",
    "C007 The Legend (China)",
    "C008 The MUMMY (China)",
    "C009 The shadow's Edge (China)",
    "E001 The Bourne Identity -2002 (English)",
    "E002 The Bourne Supremacy -2004 (English)",
    "E003 The Bourne Ultimatum 2007 (English)",
    "E004 The Bourne Legacy 2012(English)",
    "E005 Jason Bourne-2016 (English)",
    "E006 A Good Day to Die Hard -2013 (English)",
    "E007 A Legend.2024 (English)",
    "E008 Alive -2020(English)",
    "E009 Angel Has Fallen (English)",
    "E010 Black Panther Wakanda Forever 2022 (English)",
    "E011 Black Panther-2018 (English)",
    "E012 Bounty Hunters -2016 (English)",
    "E013 Bumblebee (English)",
    "E014 Captain Phillips 2013 (English)",
    "E015 Cellular (English)",
    "E016 Crouching Tiger Hidden Dragon- Sword of Destiny -2016 (English)",
    "E017 Dune Part Two -2024 (English)",
    "E018 Eternals (English)",
    "E019 Ganool.com (English)",
    "E020 Ice Sniper II 2023 (English)",
    "E021 Kingsman.The.Golden.Circle.2017 (English)",
    "E022 Kingsman.The.Secret.Service.2014(English)",
    "E023 Live Free or Die Hard - 2007 (English)",
    "E024 Mission.Impossible..The.Final.Reckoning.2025 (English)",
    "E025 Mission.Impossible.Dead.Reckoning.Part.One.2023 (English)",
    "I001 3 Idiots 2009 (India)",
    "I002 Oh My God 2012 (India)",
    "I003 PK (India)",
    "I004 Bholaa_2023 (India)",
    "IN001 Relaxing Waterfall Sounds (Instrumental)",
    "IN002 Myanmar Instrumental Piano & Violin String  (Instrumental)",
    "IN003 Guitar Love Songs Instrumental Relaxing  (Instrumental)",
    "K001 Memories.of.Murder.2003 (Korea)",
    "K002 A Dirty Carnival  (Korea)",
    "K003 A_Company_Man_2012 (Korea)",
    "K004 Bad Guys Always Die 2015 (Korea)",
    "K005 Confidential Assignment  2017 (Korea)",
    "K006 Confidential.Assignment.2.International.2022 (Korea)",
    "K007 Extreme.Job.2019 (Korean)",
    "K008 The Spy Gone North 2018 (Korea)",
    "R001 နံနက်ခင်းမေတ္တာပို့ ဓမ္မတေး  (Religous)",
    "R002 ညစဥ်ဖွင့်၍ တရားမှတ်ရင်း အိပ်စက်အနားယူပါ (Religous)",
    "R003 ပါချုပ်ဆရာတော် (Religous)",
    "R004 စိတ်ကိုထိန်းသိမ်းစောင့်ရှောက်နည်း ပါချုပ်ဆရာတော် (Religous)",
    "R005 Buddha (Religious)",
    "R006 MARAVIZAYA-MRTV (Religious)",
  ];


  List<String> musics = [
    "တရံရောအခါ (ကြည််ကြည်ဌေး)",
    "စံပါယ်ပွင့်ပြီမောင် (ကြည််ကြည်ဌေး)",
    "ကိုယ်ချစ်သူကောင်းစားရေး (ကိုကျော်ညွန့်)",
    "ယောင်္ကျားမှာလဲ အသံနဲ့ပါ (ကိုတင်လှိုင်)",
    "အမုန်းခွန်အား ပေးသနားပါ (ကိုတင်လှိုင်)",
    "မာနရှင် (ကိုမင်းနောင်)",
    "ဇရာ (ကိုမင်းနောင်)",
    "သဇင်သင်းလေသောအခါ (ကိုမြကြီး)",
    "ကိုယ့်ဒူးကိုယ်ချွန် (ကိုအုံကြီး)",
    "စိမ်းလဲ့ကန်သာ (ကိုအုံကြီး)",
    "ကိုယ့်အသက်ရှည်မျှပါခင် (ကိုအုံကြီး)",
    "ယဥ်တစ်ကိုယ်မယ် (ကိုအုံကြီး)",
  ];
}